### PR TITLE
Refactor updates as put into previous pull request plus an update that should resolve test failures.

### PR DESCRIPTION
**Pull request by davek17**
Hopefully this should pass, I don't have NUnit on my local machine. Sorry.

### CODE REVIEW

**Comment by bcemmett** [comment]
I'm not sure about this - as it stands, if you pass in null or an empty string for the api key then that won't get added to the request (only as of merging #20 yesterday though - possible you were working from an older fork?).

I'll think a little about changing the interface here - I'm reluctant to change the constructor, but now they've changed the primary authentication method it's a bit messy making people pass in nulls for what will be the most common scenario :-(

**Comment by davek17** [comment]
Sure, I was working from an older fork and saw the updates yesterday,  I left the original constructors in also, so it wouldn't be a breaking change.

**Comment by bcemmett** [comment]
Sorry for the delay, just looking at this again - any chance you could rebase it against the current version of master in this repo? Agree the change makes sense, but the diff looks confusing at the moment because it's shown against the earlier version. Cheers!

**Comment by davek17** [comment]
Will reset and recreate

**Pull request closed without merging**
